- name: Enable remi-php56 repository
  shell: yum-config-manager --enable remi,remi-php56
- name: Install PHP (main packages)
  yum: pkg={{ item }} state=latest
  with_items:
    - "{{ php_main_packages }}"
- name: Install others PHP packages 1
  yum: pkg={{ item }} state=latest
  with_items:
    - "{{ php_other_packages_1 }}"
- name: Install others PHP packages 2
  yum: pkg={{ item }} state=latest
  with_items:
    - "{{ php_other_packages_2 }}"
- name: Update PHP settings
  ini_file: dest=/etc/php.ini section={{ item.section }} option={{ item.option }} value={{ item.value }} backup=yes
  with_items:
    - "{{ php_ini_settings }}"
- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

